# Generated by Django 5.0 on 2023-12-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(max_length=200, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(null=True, upload_to='media/person_image')),
            ],
        ),
    ]
