# Generated by Django 5.0 on 2023-12-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='town',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
