# Generated by Django 5.0 on 2023-12-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_data_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='media/ability_image')),
            ],
        ),
    ]
