# Generated by Django 5.0 on 2023-12-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='img',
        ),
        migrations.CreateModel(
            name='ability_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100, null=True)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ability')),
            ],
        ),
    ]
