# Generated by Django 5.0 on 2023-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_ability_img_ability_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ability_detail',
        ),
    ]
