# Generated by Django 5.0 on 2023-12-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_experience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='experience',
            new_name='tahsil',
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
