# Generated by Django 5.0 on 2023-12-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='logo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='data_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=1000, null=True)),
                ('logo', models.ManyToManyField(to='product.data')),
            ],
        ),
    ]
