# Generated by Django 5.0 on 2023-12-28 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_data_logo_data_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_detail',
            name='logo',
        ),
        migrations.AddField(
            model_name='data_detail',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.data'),
        ),
    ]
