# Generated by Django 5.0 on 2023-12-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_ability_logo_ability_logo_delete_data_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='logo',
            new_name='adress',
        ),
    ]
