# Generated by Django 5.0 on 2023-12-28 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_logo_ability_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability_logo',
            old_name='adress',
            new_name='path1',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='adress',
        ),
        migrations.AddField(
            model_name='ability',
            name='path1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ability_logo'),
        ),
    ]
