# Generated by Django 5.0 on 2023-12-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_adress_ability_logo_path1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='path2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ability_logo'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='path1',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
