# Generated by Django 5.0 on 2023-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_ability_path2_alter_ability_path1'),
    ]

    operations = [
        migrations.CreateModel(
            name='tajrobeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
