# Generated by Django 5.0 on 2024-01-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_tajrobeh'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_work_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='media/person_image')),
            ],
        ),
        migrations.CreateModel(
            name='title_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.my_work_img')),
            ],
        ),
        migrations.DeleteModel(
            name='work',
        ),
        migrations.DeleteModel(
            name='work_img',
        ),
    ]
