# Generated by Django 4.2.5 on 2024-01-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_my_work_img_title_img_delete_work_delete_work_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_logo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='my_work_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_work', models.CharField(max_length=50, null=True)),
                ('range_work', models.CharField(max_length=50, null=True)),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.logo')),
            ],
        ),
        migrations.DeleteModel(
            name='title_img',
        ),
    ]
