# Generated by Django 5.0 on 2024-01-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_my_work_range_logo_delete_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_work_range',
        ),
    ]
