# Generated by Django 5.0 on 2024-01-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_delete_my_work_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='path2',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='ability_logo',
        ),
    ]
