# Generated by Django 4.2.5 on 2024-01-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_ability_path2_delete_ability_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='call_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/person_image')),
            ],
        ),
    ]
