# Generated by Django 5.0 on 2024-01-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register_model',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
