# Generated by Django 4.2.5 on 2024-01-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_register_model_date_alter_register_model_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='call_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/person_image')),
            ],
        ),
    ]
